#include <biomesh/exporter/gid_exporter.h>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace biomesh {

GiDExporter::GiDExporter() : precision_(6), includeStats_(true) {}

bool GiDExporter::exportMesh(const Mesh& mesh, const std::string& filename) {
    lastError_.clear();
    
    if (!mesh.isValid()) {
        setError("Invalid mesh data");
        return false;
    }
    
    if (mesh.getNodeCount() == 0) {
        setError("Mesh has no nodes");
        return false;
    }
    
    // Write main mesh file
    if (!writeMeshFile(mesh, filename)) {
        return false;
    }
    
    // Write coordinates file
    if (!writeCoordinatesFile(mesh, filename)) {
        return false;
    }
    
    // Write elements file
    if (!writeElementsFile(mesh, filename)) {
        return false;
    }
    
    return true;
}

bool GiDExporter::writeMeshFile(const Mesh& mesh, const std::string& filename) {
    std::ofstream file(filename + ".msh");
    if (!file.is_open()) {
        setError("Cannot create mesh file: " + filename + ".msh");
        return false;
    }
    
    writeHeader(file, mesh);
    
    // Write mesh information
    file << "MESH \"Biomolecule\" dimension 3 ElemType Tetrahedra Nnode 4\n";
    file << "# Generated by BioMesh\n";
    
    if (includeStats_) {
        file << "# Nodes: " << mesh.getNodeCount() << "\n";
        file << "# Elements: " << mesh.getElementCount() << "\n";
    }
    
    file << "Coordinates\n";
    file << "# x y z\n";
    
    // Write node coordinates
    const auto& nodes = mesh.getNodes();
    for (const auto& node : nodes) {
        file << std::fixed << std::setprecision(precision_) 
             << node.id << " " << node.x << " " << node.y << " " << node.z << "\n";
    }
    
    file << "End coordinates\n\n";
    
    file << "Elements\n";
    file << "# connectivity\n";
    
    // Write element connectivity
    const auto& elements = mesh.getElements();
    for (const auto& element : elements) {
        file << element.id;
        for (int nodeId : element.nodeIds) {
            file << " " << nodeId;
        }
        file << " 1\n"; // Material ID
    }
    
    file << "End elements\n";
    
    file.close();
    return true;
}

bool GiDExporter::writeCoordinatesFile(const Mesh& mesh, const std::string& filename) {
    std::ofstream file(filename + ".crd");
    if (!file.is_open()) {
        setError("Cannot create coordinates file: " + filename + ".crd");
        return false;
    }
    
    const auto& nodes = mesh.getNodes();
    for (const auto& node : nodes) {
        file << std::fixed << std::setprecision(precision_) 
             << node.id << " " << node.x << " " << node.y << " " << node.z << "\n";
    }
    
    file.close();
    return true;
}

bool GiDExporter::writeElementsFile(const Mesh& mesh, const std::string& filename) {
    std::ofstream file(filename + ".ele");
    if (!file.is_open()) {
        setError("Cannot create elements file: " + filename + ".ele");
        return false;
    }
    
    const auto& elements = mesh.getElements();
    for (const auto& element : elements) {
        file << element.id;
        for (int nodeId : element.nodeIds) {
            file << " " << nodeId;
        }
        file << "\n";
    }
    
    file.close();
    return true;
}

void GiDExporter::writeHeader(std::ofstream& file, const Mesh& mesh) {
    file << "# GiD Mesh File\n";
    file << "# Generated by BioMesh\n";
    file << "# Nodes: " << mesh.getNodeCount() << "\n";
    file << "# Elements: " << mesh.getElementCount() << "\n";
    file << "#\n";
}

void GiDExporter::setError(const std::string& error) {
    lastError_ = error;
}

} // namespace biomesh